server:
  error:
    include-message: always
  port: 8080
graphql:
  spqr:
    gui:
      enabled: true
spring:
  datasource:
    password: '@maduka1'
    url: jdbc:postgresql://localhost:5432/sprngbt1db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
#  graphql:
#    schema:
#      printer:
#        enabled: true
#    graphiql:
#      enabled: true

welcome:
  message: Welcome to daily maduka coding place !!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"


